import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
    <body className={`${geistSans.className} antialiased`} style={{ 
    backgroundImage: "url('/bg.jpg')", 
    backgroundSize: 'cover', 
    backgroundAttachment: 'fixed', 
    backgroundPosition: 'center' 
}}>
  {/* الطبقة دي بتخلي الخلفية فاتحة شوية عشان الكلام يظهر بوضوح */}
  <div className="min-h-screen bg.jpg/40 backdrop-blur-[1px]">
    {children}
  </div>
</body>
    </html>
  );
}
